/**
 * Lista blanca de canales IPC. La usa el preload (que no carga zod) para rechazar
 * cualquier canal que no esté en el contrato. Un test comprueba que coincide con
 * `ipcSchemas` de `ipc.ts`.
 */
export const IPC_CHANNELS = [
  'app:info',
  'app:activity',
  'vault:status',
  'vault:pickFolder',
  'vault:create',
  'vault:open',
  'vault:unlock',
  'vault:recover',
  'vault:lock',
  'vault:close',
  'vault:changePassword',
  'vault:rotateKey',
  'settings:setAutoLock',
  'settings:setAppearance',
  'clipboard:writeSecret',
  'data:entities',
  'data:fields',
  'data:createField',
  'data:updateField',
  'data:reorderFields',
  'data:deleteField',
  'data:restoreField',
  'data:formulaProblem',
  'data:views',
  'data:createView',
  'data:updateView',
  'data:deleteView',
  'data:query',
  'data:get',
  'data:create',
  'data:createInverseField',
  'files:pick',
  'files:upload',
  'files:info',
  'files:setMeta',
  'files:export',
  'versions:list',
  'versions:create',
  'versions:restore',
  'tasks:summary',
  'briefs:templates',
  'briefs:setTemplates',
  'profile:get',
  'profile:set',
  'data:update',
  'data:setLinks',
  'data:duplicate',
  'data:trash',
  'data:restore',
  'data:purge',
  'data:trashList',
  'data:setTrashDays',
  'data:history',
  'data:search',
  'data:undo',
  'data:redo',
  'data:undoState',
  'data:exportCsv',
] as const

export const IPC_EVENTS = ['vault:changed', 'data:changed'] as const
