import {
  Activity,
  Archive,
  Atom,
  Award,
  Banknote,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleDot,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Contact,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Droplet,
  Euro,
  Eye,
  FileChartColumn,
  FileText,
  Files,
  Film,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Funnel,
  Gauge,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Heart,
  Hexagon,
  House,
  IdCard,
  Image,
  Images,
  Inbox,
  Infinity as InfinityIcon,
  Kanban,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  List,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Moon,
  MousePointerClick,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PenTool,
  Percent,
  Phone,
  PiggyBank,
  Pin,
  Plane,
  Presentation,
  Puzzle,
  Radar,
  Receipt,
  ReceiptEuro,
  Rocket,
  Rss,
  ScanEye,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  SquareCheckBig,
  Star,
  StickyNote,
  Store,
  Sun,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Video,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Iconos de las secciones (D-094): un catálogo cerrado de Lucide (ISC) para elegir en
 * Ajustes → Apariencia. Solo se importan estos, así que el resto de Lucide no entra en la app.
 */
export const ICONS: Record<string, LucideIcon> = {
  house: House,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  'user-plus': UserPlus,
  contact: Contact,
  'id-card': IdCard,
  'notebook-pen': NotebookPen,
  'sticky-note': StickyNote,
  'list-todo': ListTodo,
  'square-check-big': SquareCheckBig,
  'clipboard-list': ClipboardList,
  'file-text': FileText,
  newspaper: Newspaper,
  megaphone: Megaphone,
  image: Image,
  images: Images,
  clapperboard: Clapperboard,
  film: Film,
  video: Video,
  camera: Camera,
  'chart-line': ChartLine,
  'chart-column': ChartColumn,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  activity: Activity,
  gauge: Gauge,
  radar: Radar,
  target: Target,
  crosshair: Crosshair,
  funnel: Funnel,
  receipt: Receipt,
  'receipt-euro': ReceiptEuro,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  banknote: Banknote,
  'credit-card': CreditCard,
  euro: Euro,
  percent: Percent,
  calculator: Calculator,
  'file-chart-column': FileChartColumn,
  presentation: Presentation,
  'folder-open': FolderOpen,
  folder: Folder,
  files: Files,
  archive: Archive,
  box: Box,
  package: Package,
  paperclip: Paperclip,
  wrench: Wrench,
  hammer: Hammer,
  'trash-2': Trash2,
  settings: Settings,
  lock: Lock,
  briefcase: Briefcase,
  'building-2': Building2,
  store: Store,
  handshake: Handshake,
  rocket: Rocket,
  zap: Zap,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flag: Flag,
  bookmark: Bookmark,
  pin: Pin,
  tag: Tag,
  tags: Tags,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clock: Clock,
  timer: Timer,
  bell: Bell,
  mail: Mail,
  inbox: Inbox,
  send: Send,
  'message-square': MessageSquare,
  phone: Phone,
  globe: Globe,
  link: Link,
  'map-pin': MapPin,
  map: Map,
  compass: Compass,
  music: Music,
  mic: Mic,
  palette: Palette,
  'pen-tool': PenTool,
  brush: Brush,
  lightbulb: Lightbulb,
  brain: Brain,
  bot: Bot,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  cloud: Cloud,
  shield: Shield,
  key: Key,
  eye: Eye,
  'scan-eye': ScanEye,
  search: Search,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'layout-dashboard': LayoutDashboard,
  kanban: Kanban,
  table: Table,
  list: List,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  truck: Truck,
  gift: Gift,
  ticket: Ticket,
  coffee: Coffee,
  book: Book,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  award: Award,
  trophy: Trophy,
  gem: Gem,
  crown: Crown,
  smile: Smile,
  'thumbs-up': ThumbsUp,
  'share-2': Share2,
  rss: Rss,
  puzzle: Puzzle,
  atom: Atom,
  infinity: InfinityIcon,
  'circle-dot': CircleDot,
  hexagon: Hexagon,
  shapes: Shapes,
  'mouse-pointer-click': MousePointerClick,
  plane: Plane,
  car: Car,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  flame: Flame,
  droplet: Droplet,
}

/** Icono de serie de cada sección; las colecciones del usuario usan «layers». */
export const DEFAULT_SECTION_ICONS: Record<string, string> = {
  perfil: 'user-round',
  inicio: 'house',
  notas: 'notebook-pen',
  clientes: 'users',
  contactos: 'contact',
  tareas: 'list-todo',
  briefs: 'clipboard-list',
  campanas: 'megaphone',
  creatividades: 'images',
  analisis: 'chart-line',
  facturacion: 'wallet',
  facturas: 'receipt-euro',
  gastos: 'banknote',
  horas: 'timer',
  informes: 'file-chart-column',
  documentos: 'folder-open',
  herramientas: 'wrench',
  papelera: 'trash-2',
  ajustes: 'settings',
}

export const COLLECTION_ICON = 'layers'

/** Nombre del icono de una sección: el elegido, el de serie o el de las colecciones. */
export function sectionIconName(id: string, chosen: Record<string, string>): string {
  const pick = chosen[id]
  if (pick && pick in ICONS) return pick
  return DEFAULT_SECTION_ICONS[id] ?? COLLECTION_ICON
}

export function SectionIcon({ name, size = 16 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? ICONS[COLLECTION_ICON]!
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" focusable="false" />
}
